<?php

$config = [
    [
        "db" => "subordination",
        "name" => "r_podch",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "SELECT podr_ruk,adm_prof,adm_podr FROM ",
        "where" => "",
        "ai" => "id",
        "map" => [
            "podr_ruk" => "varchar(2)", "adm_prof" => "varchar(10)", "adm_podr" => "varchar(2)",
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "subordination",
        "name" => "r_podch_zbt",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["podr", "prof"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "podr" => "varchar(2)", "podr_ruk" => "varchar(2)", "prof" => "varchar(10)", "adm_podr" => "varchar(2)", "adm_prof" => "varchar(10)", "fun_podr" => "varchar(2)", "fun_prof" => "varchar(10)", "fun_pr" => "int(1)",
            "del_date" => "date", "kod_pr" => "varchar(2)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "subordination",
        "name" => "r254",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "subordination",
        "name" => "kotp",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["tn","beg","endo"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "SELECT tn,npr,beg,endo,kind,ney,od,tn_rab FROM",
        "where" => "WHERE (DATE() BETWEEN beg AND endo) and (kind = 70 or kind=72)",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "subordination",
        "name" => "FSCHTAT",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "subordination",
        "name" => "osdalu",
        "path" => "",
        "pr_key" => "tn",
        "indexes" => ["kat", "fm", "opd", "podr", "ima", "oth", "sex"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "podr" => "varchar(10)", "tn" => "varchar(6)", "fm" => "varchar(40)", "ima" => "varchar(20)", "oth" => "varchar(14)", "kat" => "varchar(2)", "opd" => "varchar(10)", "dr" => "date",
            "razr" => "int(1)", "setka" => "varchar(2)", "sex" => "int(1)", "sisopl" => "int(1)", "dpr" => "date", "gorod" => "varchar(12)", "ulica" => "int(4)", "dom" => "int(4)",
            "kor_kv" => "varchar(6)", "tlf" => "int(7)", "usl" => "int(1)", "dos" => "date", "ps" => "varchar(14)", "nps" => "varchar(14)", "vdh" => "varchar(40)", "dvdp" => "date",
            "ad_proj" => "varchar(40)", "smp" => "int(2)", "vid_rab" => "int(1)", "rb" => "decimal(4,1)", "ro" => "int(9)"
        ],
        "engine" => "InnoDB",
    ],
];

$config_child = [
    [
        "db" => "subordination",
        "name" => "staff",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [
            [
                "fk_name" => "fkpeople", "fk_col" => "tn_people",
                "fk_ref_table" => "people",
                "fk_ref_col" => "tn",
                "action_del" => "SET NULL",
                "action_upd" => "CASCADE"
            ]
        ],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "subordination",
        "name" => "people",
        "path" => "",
        "pr_key" => "tn",
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => null,
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "subordination",
        "name" => "tree",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [
            [
                // "fk_name" => "fkstaff", "fk_col" => "staff",
                // "fk_ref_table" => "staff",
                // "fk_ref_col" => "id",
                // "action_del" => "CASCADE",
                // "action_upd" => "CASCADE"
            ]
        ],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
];
return [$config, $config_child];
