<?php

$config = [
    [
        "db" => "nci_test",
        "name" => "r233",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["kpost"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [
            "id" => "int(11)", "kod_str" => "varchar(3)", "kpost" => "varchar(8)", "npost" => "varchar(200)", "gg" => "int(2)", "r_s" => "varchar(35)", "bank" => "varchar(50)", "mfo" => "varchar(20)",
            "tlx" => "varchar(20)", "fax" => "varchar(20)", "tlf" => "varchar(20)", "gorod" => "varchar(20)", "ss" => "varchar(20)", "fio" => "varchar(20)", "kod_pr" => "varchar(20)", "jdstn" => "varchar(1)",
            "adres" => "varchar(100)", "dat_add" => "date", "dat_korr" => "date", "inn" => "varchar(20)", "kpp" => "varchar(20)", "kpost_m" => "varchar(8)", "pr_ko" => "tinyint(1)", "metka" => "tinyint(1)",
            "pr_auto" => "varchar(1)", "pr_otop" => "tinyint(1)", "indeks" => "varchar(6)", "s_point" => "varchar(10)", "n_point" => "varchar(39)", "s_ulic" => "varchar(10)", "n_ulic" => "varchar(30)", "s_dom" => "varchar(10)",
            "n_dom" => "varchar(30)", "s_obl" => "varchar(10)", "n_obl" => "varchar(30)", "s_raion" => "varchar(10)", "n_raion" => "varchar(30)", "usr_add" => "varchar(8)", "usr_korr" => "varchar(8)", "minprom" => "varchar(1)",
            "iban" => "varchar(35)", "bik" => "varchar(20)", "perenos" => "tinyint(1)"
        ],
        "engine" => "InnoDB",
    ],

    [
        "db" => "nci_test",
        "name" => "p160901",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["id", "ddog", "pr_zakr", "podr", "year"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "id" => "varchar(4)", "year" => "varchar(2)", "num_dog" => "varchar(25)", "ddog" => "date", "kpost" => "varchar(8)", "str_kod" => "varchar(3)", "npost" => "varchar(60)", "nchief" => "varchar(30)",
            "vid_dog" => "varchar(2)", "svn_kod" => "varchar(3)", "summa" => "decimal(15,2)", "kon_beg" => "date", "kon_end" => "date", "podr" => "varchar(8)", "ispol" => "varchar(6)", "d_opl" => "date",
            "d_reg" => "date", "ds" => "varchar(1)", "city_kod" => "varchar(6)", "d_create" => "date", "d_modif" => "date", "tn" => "varchar(6)", "tn_edit" => "varchar(6)", "gorod" => "varchar(20)",
            "metka" => "varchar(1)", "usl_opl" => "varchar(1)", "podpis" => "varchar(6)", "unn" => "varchar(12)", "pok_prod" => "varchar(1)", "usl_post" => "varchar(3)",
            "tex" => "varchar(60)", "dat_tender" => "date", "nom_tender" => "varchar(15)", "editp" => "varchar(1)", "preten" => "varchar(1)", "check_sum" => "varchar(1)", "tip_d" => "varchar(2)", "zakr" => "varchar(1)",
            "tipovoi" => "varchar(1)", "posre" => "varchar(1)",
            "pr_zakr" => "int(1)", "data_zakr" => "date", "npost_f" => "varchar(250)", "tn_hostel" => "varchar(6)", "dog_new_id" => "bigint(10)", "posre_vid" => "varchar(4)", "end" => "date", "pr_pril" => "varchar(1)",
            "kod_pr_dog" => "varchar(2)", "let_credit" => "tinyint(1)",
            "check_byn" => "decimal(15,2)", "check_vdog" => "decimal(15,2)", "sum_actual" => "decimal(15,2)", "svn_actual" => "varchar(3)", "p160958_id" => "int(4)", "p160960_id" => "int(4)", "check_vdnb" => "decimal(15,2)"
        ],
        "engine" => "InnoDB",

    ],

    [
        "db" => "nci_test",
        "name" => "pn502u_2",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["det", "naim"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "det" => "varchar(12)", "eto" => "varchar(2)", "naim" => "varchar(20)", "edi" => "varchar(3)", "cena" => "decimal(12,2)", "stm_mat" => "decimal(12,2)", "stm_usl" => "decimal(12,2)", "kbs" => "varchar(6)",
            "kz" => "varchar(6)", "comment" => "varchar(20)", "blok" => "varchar(1)", "data_kor" => "date", "who_is" => "varchar(20)", "tn" => "varchar(6)", "nzap" => "bigint(10)", "kod_pr" => "varchar(2)",
            "nds" => "decimal(6,2)", "sum_nds" => "decimal(12,2)"
        ],
        "engine" => "InnoDB",
    ],

    [
        "db" => "nci_test",
        "name" => "R120Unew",
        "path" => "",
        "pr_key" => "kmat",
        "indexes" => ["kedizm"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kvxpeo" => "varchar(1)", "func" => "varchar(1)", "kmat" => "varchar(10)", "naim" => "varchar(58)", "kedizm" => "varchar(3)", "cena" => "decimal(10,2)", "kbs" => "varchar(6)", "dat_korr" => "date",
            "pr_cen" => "varchar(1)", "nds" => "decimal(6,2)", "nzap" => "bigint(10)", "izm_cen" => "varchar(2)", "id_ksu" => "varchar(10)", "nz" => "varchar(6)", "gz" => "varchar(4)"
        ],
        "engine" => "InnoDB",
    ],

    [
        "db" => "nci_test",
        "name" => "R241",
        "path" => "",
        "pr_key" => "eizm",
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "eizm" => "varchar(3)", "naimeizm" => "varchar(10)", "nm_ei" => "varchar(35)", "uom" => "varchar(3)"
        ],
        "engine" => "InnoDB",
    ],

    [
        "db" => "nci_test",
        "name" => "PN161",
        "path" => "",
        "pr_key" => "str_kod",
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "str_kod" => "varchar(40)", "str_k2" => "varchar(20)", "str_name_a" => "varchar(40)", "str_kod" => "varchar(3)", "str_k2" => "varchar(2)", "str_name" => "varchar(20)", "str_n_of" => "varchar(65)", "nds" => "decimal(6,2)",
            "nds" => "decimal(6,2)", "kstr" => "varchar(3)", "nstr" => "varchar(20)"
        ],
        "engine" => "InnoDB",
    ],

    [
        "db" => "nci_test",
        "name" => "BD314S",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["mat", "ed_iz"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "mat" => "varchar(9)", "name" => "varchar(120)", "ed_iz" => "varchar(10)", "cena" => "decimal(13,2)", "schet" => "varchar(6)", "k_ed_iz" => "varchar(3)", "id_ksu" => "varchar(10)"
        ],
        "engine" => "InnoDB",
    ],

    [
        "db" => "nci_test",
        "name" => "rs_mzx",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["kod", "k_val", "tranzit"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod" => "varchar(3)", "rs_mzx" => "varchar(28)", "k_val" => "varchar(3)", "prim" => "varchar(50)", "bs" => "varchar(6)", "date_start" => "date", "date_end" => "date", "n_dog" => "varchar(20)",
            "kod_pr" => "varchar(2)", "rs_old" => "varchar(28)", "date_del" => "date", "d_modif" => "date", "to_iban" => "varchar(1)", "tranzit" => "varchar(3)", "kod_podr" => "varchar(4)", "n_dog_345" => "varchar(20)",
        ],
        "engine" => "InnoDB",
    ],

    /** 
     * @todo на этот конфиг ругается т.к такой dbf нет
     */

    // [
    //     "db" => "nci_test",
    //     "name" => "bank_mzx",
    //     "path" => "id",
    //     "pr_key" => null,
    //     "indexes" => [],
    //     "foreignkeys" => [],
    //     "charset" => "utf8",
    //     "prefix" => "nci_",
    //     "select" => "",
    //     "ai" => "",
    // ],

    /** 
     * @todo на этот конфиг ругается т.к такой dbf нет
     */

    // [
    //     "db" => "nci_test",
    //     "name" => "bank_gr",
    //     "path" => "grup",
    //     "pr_key" => null,
    //     "indexes" => [],
    //     "foreignkeys" => [],
    //     "charset" => "utf8",
    //     "prefix" => "nci_",
    //     "select" => "",
    //     "ai" => "",
    // ],

    [
        "db" => "nci_test",
        "name" => "r029",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["gr", "rab"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "gr" => "varchar(2)", "rab" => "varchar(2)", "item" => "varchar(3)", "kodst" => "varchar(2)", "zatr" => "varchar(6)", "old_zatr" => "varchar(6)", "nitem" => "varchar(254)", "zatr_gk" => "varchar(6)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "r029rab",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["gr"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "gr" => "varchar(2)", "rab" => "varchar(2)", "nrab" => "varchar(250)", "zatr" => "varchar(6)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "r029gr",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["gr"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "gr" => "varchar(2)", "ngr" => "varchar(100)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "r029item",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["gr", "rab", "item"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "gr" => "varchar(2)", "rab" => "varchar(2)", "item" => "varchar(3)", "zatr" => "varchar(6)", "nitem" => "varchar(250)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "bank_korr",
        "path" => "",
        "pr_key" => "id",
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "id" => "varchar(5)", "kod_kor" => "varchar(3)", "kor_name" => "varchar(100)", "adr_kor_b" => "varchar(100)", "bik" => "varchar(20)", "swift" => "varchar(20)", "date_start" => "date", "date_end" => "date",
            "date_del" => "date", "d_modif" => "date", "inn" => "varchar(10)", "country" => "varchar(3)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "tip_sch",
        "path" => "",
        "pr_key" => "tip",
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod" => "varchar(3)", "name" => "varchar(20)", "tip" => "int(1)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "r243pr",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["kod_pr"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod_pr" => "varchar(2)", "npr" => "varchar(50)", "sp" => "tinyint(1)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "r243sl",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["kod_sl", "kod_pr", "nsl", "knsl", "data_do", "data_ot"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod_pr" => "varchar(2)", "kod_sl" => "varchar(2)", "nsl" => "varchar(50)", "knsl" => "varchar(20)", "data_ot" => "date", "data_do" => "date", "priz_arh" => "int(1)", "tn_ruk" => "varchar(6)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "r243admu",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["kod_admu", "kod_ceh", "kod_pr", "nadmu", "knadmu", "priz_arh", "data_do", "data_ot"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod_pr" => "varchar(2)", "kod_ceh" => "varchar(2)", "kod_dir" => "varchar(2)", "kod_admu" => "varchar(2)", "nadmu" => "varchar(100)", "knadmu" => "varchar(20)", "data_ot" => "date", "data_do" => "date",
            "duvz" => "date", "priz_arh" => "int(1)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "r243CEH",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["kod_ceh", "kod_pr", "kod_sl", "kod_gr", "nceh", "knceh", "priz_arh", "data_do", "data_ot"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod_pr" => "varchar(2)", "kod_ceh" => "varchar(2)", "nceh" => "varchar(100)", "knceh" => "varchar(20)", "kod_gr" => "varchar(2)", "kod_sl" => "varchar(2)", "kod_vid" => "varchar(2)", "data_ot" => "date",
            "data_do" => "date", "duvz" => "date", "priz_arh" => "int(1)", "nom_pol" => "varchar(20)", "data_vvod" => "date", "nom_prik" => "varchar(4)", "prim" => "varchar(20)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "r243mbr",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["kod_master", "kod_brig", "kod_admu", "kod_ceh", "kod_pr", "nbrig", "knbrig", "priz_arh", "data_do", "data_ot"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod_pr" => "varchar(2)", "kod_ceh" => "varchar(2)", "kod_dir" => "varchar(2)", "kod_admu" => "varchar(2)", "kod_master" => "varchar(2)",  "kod_brig" => "varchar(2)", "kod_tm" => "varchar(2)", "nbrig" => "varchar(100)",
            "knbrig" => "varchar(20)", "data_ot" => "date", "data_do" => "date", "duvz" => "date", "priz_arh" => "int(1)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "r252",
        "path" => "",
        "pr_key" => "kateg",
        "indexes" => ["gr", "rab"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kateg" => "varchar(2)", "naim" => "varchar(40)", "gr_pp" => "int(1)", "gr_npp" => "varchar(2)", "gr_kat" => "int(1)", "gr_nkat" => "varchar(15)", "gr_vrem" => "int(1)", "gr_nvrem" => "varchar(15)",
            "k_aup" => "int(1)", "nk_aup" => "varchar(10)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "R148TEK",
        "path" => "",
        "pr_key" => "tn",
        "indexes" => ["kod_pr", "cex", "uch", "mast", "brig", "prof", "kat", "fio"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "tn" => "varchar(6)", "kod_pr" => "varchar(2)", "cex" => "varchar(2)", "uch" => "varchar(2)", "mast" => "varchar(2)", "brig" => "varchar(2)", "prof" => "varchar(10)", "kat" => "varchar(2)",
            "fio" => "varchar(20)", "setka" => "varchar(2)", "sisopl" => "int(1)", "razr" => "int(1)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "R254",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["proff", "kprof", "gost"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "proff" => "varchar(5)", "kprof" => "varchar(8)", "nprof" => "varchar(35)", "pnprof" => "varchar(150)", "prizm" => "varchar(1)", "gost" => "varchar(10)", "v_r" => "int(1)", "d_create" => "date",
            "kod_ur" => "varchar(2)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "kosuv",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["tn", "kod_pr", "cex", "uch"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "postn" => "varchar(5)", "tn" => "varchar(6)", "kod_pr" => "varchar(2)", "cex" => "varchar(2)", "uch" => "varchar(2)", "master" => "varchar(2)", "brig" => "varchar(2)", "podr" => "varchar(8)",
            "fm" => "varchar(40)", "ima" => "varchar(15)", "oth" => "varchar(15)", "sex" => "int(1)", "sop" => "int(1)", "dos" => "date", "dns" => "date", "d_13z" => "date", "d_zav" => "date",
            "dpr" => "date", "dokr" => "date", "upr" => "int(1)", "npr" => "varchar(6)", "odpr" => "date", "ist_kom" => "int(2)", "opd" => "varchar(10)", "primpr" => "varchar(3)",
            "kolst" => "decimal(4,2)", "vid_rab" => "int(1)", "osn" => "int(1)", "xpr" => "int(1)", "ispsr" => "int(2)", "rejim" => "int(2)", "kat" => "varchar(2)", "razr" => "int(1)",
            "setka" => "varchar(2)", "sisopl" => "int(1)", "usl" => "int(1)", "nspis" => "varchar(1)", "ok" => "int(9)", "nadbawka" => "int(9)", "procn" => "decimal(6,2)", "dopotp" => "int(2)",
            "ochotp" => "int(2)", "marka" => "varchar(10)", "gruz_p" => "decimal(5,2)", "vid_u" => "int(1)", "obr" => "int(1)", "uz" => "int(5)", "fob" => "int(1)", "spd" => "int(7)",
            "kfd" => "int(7)", "ndip" => "varchar(10)", "ddip" => "date", "dlp" => "varchar(10)", "pmr" => "varchar(30)", "pru" => "int(4)", "duv" => "date", "tnkogo" => "int(6)",
            "vds" => "int(1)", "dds" => "date", "mr" => "varchar(40)", "dr" => "date", "nc" => "int(3)", "ps" => "varchar(14)", "nps" => "varchar(14)", "vdh" => "varchar(40)",
            "dvdp" => "date", "das" => "varchar(25)", "gorod" => "varchar(12)", "ulica" => "int(4)", "dom" => "int(4)", "kor_kv" => "varchar(6)", "tlf" => "int(7)", "ad_proj" => "varchar(40)",
            "smp" => "int(2)", "rb" => "decimal(4,1)", "ro" => "int(9)", "pl" => "decimal(6,2)", "kol_pl" => "int(2)", "dog" => "date", "m_otv" => "int(1)", "pruz" => "int(4)",
            "duvz" => "date", "osn_uv" => "varchar(70)", "pr_tek" => "int(1)", "odprps" => "date", "nprps" => "varchar(6)", "dprps" => "date", "okp" => "int(9)", "nadbawkap" => "int(9)",
            "dataizm" => "varchar(6)", "npp_k" => "int(6)", "gr_k" => "varchar(2)", "cmrpun" => "varchar(28)", "cmrray" => "varchar(28)", "cmrobl" => "varchar(28)", "cmrstran" => "varchar(28)", "cpasser" => "varchar(10)",
            "npasnom" => "varchar(9)", "cpaslnom" => "varchar(14)", "cnzl" => "varchar(14)", "ctipf" => "varchar(1)", "npindex" => "varchar(6)", "cgrzl" => "varchar(1)", "pr_fszn" => "int(1)", "data_fszn" => "date",
            "soato" => "varchar(10)", "korpus" => "varchar(2)", "kvartira" => "varchar(5)", "kem_vyd" => "int(3)", "vid_dok" => "int(1)", "u_z" => "int(7)", "d_110" => "date", "dm" => "varchar(3)",
            "inic" => "varchar(4)", "reg_n" => "date", "reg_k" => "date", "ad_preb" => "varchar(40)", "d_deis" => "date", "tn_rab" => "varchar(6)", "data" => "date", "nld" => "varchar(6)",
            "data_nld" => "date", "int_group" => "varchar(4)", "serial_num" => "varchar(3)", "kvart" => "varchar(6)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "osdalu",
        "path" => "",
        "pr_key" => "tn",
        "indexes" => ["kat", "fm", "opd", "podr", "ima", "oth"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "podr" => "varchar(10)", "tn" => "varchar(6)", "fm" => "varchar(40)", "ima" => "varchar(20)", "oth" => "varchar(14)", "kat" => "varchar(2)", "opd" => "varchar(10)", "dr" => "date",
            "razr" => "int(1)", "setka" => "varchar(2)", "sex" => "int(1)", "sisopl" => "int(1)", "dpr" => "date", "gorod" => "varchar(12)", "ulica" => "int(4)", "dom" => "int(4)",
            "kor_kv" => "varchar(6)", "tlf" => "int(7)", "usl" => "int(1)", "dos" => "date", "ps" => "varchar(14)", "nps" => "varchar(14)", "vdh" => "varchar(40)", "dvdp" => "date",
            "ad_proj" => "varchar(40)", "smp" => "int(2)", "vid_rab" => "int(1)", "rb" => "decimal(4,1)", "ro" => "int(9)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "r244",
        "path" => "",
        "pr_key" => "tarif",
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "tarif" => "varchar(2)", "chts0" => "decimal(13,4)", "chts1" => "decimal(13,4)", "chts2" => "decimal(13,4)", "chts3" => "decimal(13,4)", "chts4" => "decimal(13,4)", "chts5" => "decimal(13,4)", "chts6" => "decimal(13,4)",
            "datai" => "date"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "education",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["tn", "u_z", "spec", "kfd", "kol_obr"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "pr_ok" => "varchar(1)", "tn" => "varchar(6)", "u_z" => "int(7)", "fac" => "varchar(30)", "spec" => "int(7)", "dps" => "date", "dok" => "date", "ndip" => "varchar(10)",
            "kfd" => "int(7)", "f_ob" => "int(7)", "pr_uch" => "varchar(1)", "kol_obr" => "int(1)", "uz" => "varchar(80)", "obr" => "int(7)", "uz1" => "varchar(50)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "KOTP",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["tn", "kind", "beg", "endo"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "tn" => "varchar(6)", "npr" => "varchar(6)", "odpr" => "date", "dpr" => "date", "beg" => "date", "endo" => "date", "dp1" => "date", "dp2" => "date",
            "kind" => "int(2)", "ney" => "varchar(2)", "od" => "int(5)", "m11" => "int(2)", "duvz" => "date", "osn_ot" => "int(2)", "ochotp" => "int(2)", "dopotp" => "int(2)",
            "kolotp" => "int(2)", "vytotp" => "int(2)", "stjotp" => "int(2)", "mnsotp" => "int(2)", "tn_rab" => "varchar(6)",  "time" => "varchar(5)", "data" => "date", "kney_b" => "varchar(3)",
            "vyt_f" => "int(2)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "SPR",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["kod", "kk7"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kk7" => "varchar(2)", "ll" => "varchar(2)", "kod" => "int(7)", "name" => "varchar(75)", "priznak" => "varchar(1)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "r_podch",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["podr", "prof"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "podr" => "varchar(2)", "podr_ruk" => "varchar(2)", "prof" => "varchar(10)", "adm_podr" => "varchar(2)", "adm_prof" => "varchar(10)", "fun_podr" => "varchar(2)", "fun_prof" => "varchar(10)", "fun_pr" => "int(1)",
            "del_date" => "date", "kod_pr" => "varchar(2)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "R254KKK",
        "path" => "",
        "pr_key" => "kod",
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod" => "varchar(1)", "naim" => "varchar(20)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "R254KPD",
        "path" => "",
        "pr_key" => "kod",
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod" => "varchar(1)", "naim" => "varchar(35)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "NOV130",
        "path" => "",
        "pr_key" => "tab",
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod_pr" => "varchar(2)", "zex" => "varchar(2)", "tab" => "varchar(6)", "fio" => "varchar(20)", "yca" => "varchar(2)", "prof" => "varchar(10)", "sisopl" => "varchar(1)", "kat" => "varchar(2)",
            "tk" => "decimal(6,3)", "setka" => "varchar(2)", "razr" => "varchar(1)", "cts" => "decimal(12,4)", "nadbawka" => "decimal(12,4)", "itogo" => "decimal(12,4)", "proc_77" => "int(2)", "nad_77" => "decimal(12,4)",
            "ctss" => "decimal(12,4)", "ndbs" => "decimal(12,4)", "itogo_s" => "decimal(12,4)", "procs_77" => "int(2)", "nads_77" => "decimal(12,4)", "n_prof" => "varchar(35)", "n_cts" => "varchar(2)", "k5" => "int(2)",
            "chts1" => "int(8)", "pri1" => "varchar(1)", "master" => "varchar(2)", "brig" => "varchar(2)", "k1" => "int(2)", "k2" => "int(2)", "k3" => "int(2)", "kontrakt" => "varchar(3)",
            "priz" => "varchar(1)", "proc_s" => "int(2)", "odprps" => "date", "dog" => "date"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "r006",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["stot", "stdo"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "stot" => "decimal(4,1)", "stdo" => "int(2)", "prop" => "int(2)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "r009",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod_pr" => "varchar(2)", "cex" => "varchar(2)", "uch" => "varchar(2)", "plan" => "int(2)", "fakt" => "decimal(5,2)", "vybor" => "int(1)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "r_podch_zbt",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["podr", "prof"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "podr" => "varchar(2)", "podr_ruk" => "varchar(2)", "prof" => "varchar(10)", "adm_podr" => "varchar(2)", "adm_prof" => "varchar(10)", "fun_podr" => "varchar(2)", "fun_prof" => "varchar(10)", "fun_pr" => "int(1)",
            "del_date" => "date", "kod_pr" => "varchar(2)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "FSCHTAT",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["tn", "gr", "kod_pr", "podr", "tnvrrab", "vid_rab", "cex", "kprofpl", "kateg"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod_pr" => "varchar(2)", "nal_vak_o" => "int(1)", "d_vo_vak" => "date", "podr" => "varchar(8)", "cex" => "varchar(2)", "uch" => "varchar(2)", "master" => "varchar(2)", "brig" => "varchar(2)", "kateg" => "varchar(2)",
            "kprofpl" => "varchar(10)", "kolst" => "decimal(4,2)", "primpr" => "varchar(30)", "gr" => "varchar(2)", "fstr" => "int(3)", "razrpl" => "int(1)", "setkapl" => "varchar(2)", "sisoplpl" => "int(1)",
            "uslpl" => "int(1)", "kzat" => "varchar(6)", "okladpl" => "decimal(14,4)", "nadb1pl" => "decimal(14,4)", "nadb2pl" => "decimal(14,4)", "procvr" => "decimal(6,2)", "procpr" => "decimal(4,1)", "nrm" => "varchar(4)",
            "kdoo" => "int(2)", "kddo" => "int(2)", "nspis" => "varchar(1)", "nprik" => "varchar(5)", "dprik" => "date", "markapl" => "varchar(20)", "koef" => "decimal(6,3)", "gruzpl" => "decimal(5,2)",
            "prim3" => "varchar(3)", "vakot" => "date", "vakdo" => "date", "tn" => "varchar(6)", "fm" => "varchar(20)", "vid_rab" => "int(1)", "xpr" => "int(1)", "dokr" => "date",
            "tnvrrab" => "varchar(6)", "dokrvr" => "date", "dots" => "date", "kat" => "varchar(2)", "razr" => "int(1)", "setka" => "varchar(2)", "sisopl" => "int(1)", "usl" => "int(1)",
            "ok" => "decimal(14,4)", "nadbawka" => "decimal(14,4)", "nadb2f" => "decimal(14,4)", "procn" => "decimal(6,2)", "ochotp" => "int(2)", "dopotp" => "int(2)", "marka" => "varchar(20)", "gruz_p" => "decimal(5,2)",
            "okp" => "int(9)", "nadbawkap" => "decimal(14,4)", "okladplp" => "decimal(14,4)", "nadb1plp" => "decimal(14,4)", "nadb2plp" => "decimal(14,4)", "dataizm" => "varchar(6)", "npp" => "int(6)", "tn_rab" => "varchar(6)",
            "data_r" => "date", "time" => "varchar(5)", "p_pr" => "varchar(1)", "t_razrpl" => "decimal(4,1)", "t_razrf" => "decimal(4,1)", "tk_pl" => "decimal(6,3)", "tk_f" => "decimal(6,3)", "proc_77pl" => "int(3)",
            "proc_77f" => "int(3)", "nad_77pl" => "decimal(14,4)", "nad77plp" => "decimal(14,4)", "nad_77f" => "decimal(14,4)", "tn_vak" => "varchar(6)", "tnvr_vak" => "varchar(6)",  "prinad" => "int(2)", "clas" => "int(1)",
            "opd" => "varchar(10)", "nom_pol" => "varchar(20)", "data_vvod" => "date", "nom_prik" => "varchar(4)",  "prim" => "varchar(20)", "nal_instr" => "int(1)", "k1" => "int(2)", "k2" => "int(2)",
            "k3" => "int(2)", "k5" => "int(3)", "rab_mesto" => "int(1)", "d_r_mesto" => "date", "odprps" => "date", "data_o" => "date", "int_group" => "varchar(4)", "serial_num" => "varchar(3)",
            "int_groupf" => "varchar(4)", "seriial_nf" => "varchar(3)", "data_arm" => "date", "tn_voen" => "varchar(6)", "soldat" => "text"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "uch_z",
        "path" => "",
        "pr_key" => "kod",
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod" => "int(7)",  "kod_new" => "int(7)", "name_k" => "varchar(7)", "name_p" => "varchar(60)", "adres" => "varchar(50)", "tel" => "varchar(8)", "pr_uch" => "varchar(1)", "r_s" => "varchar(20)",
            "unn" => "varchar(9)", "bank" => "varchar(50)", "gorod_u" => "varchar(15)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "SPR_ALG",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["kod_pr", "kod_ceh", "kod_admu", "kateg", "kprofpl"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod_pr" => "varchar(2)", "kod_ceh" => "varchar(2)", "kod_admu" => "varchar(2)", "kod_brig" => "varchar(4)", "kateg" => "varchar(2)", "kprofpl" => "varchar(10)", "n_cts" => "varchar(2)", "n_alg" => "int(2)"
        ],
        "engine" => "InnoDB",
    ],
    [
        "db" => "nci_test",
        "name" => "R243DIR",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["kod_pr", "kod_ceh", "kod_dir", "priz_arh"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "nci_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [
            "kod_pr" => "varchar(2)", "kod_ceh" => "varchar(2)", "kod_dir" => "varchar(2)", "ndir" => "varchar(100)", "kndir" => "varchar(20)", "data_ot" => "date", "data_do" => "date", "duvz" => "date",
            "priz_arh" => "int(1)"
        ],
        "engine" => "InnoDB",
    ],

];
$config_child = [
    // [
    //     "db" => "nci_test",
    //     "name" => "_all_time_dig28",
    //     "path" => "",
    //     "pr_key" => null,
    //     "indexes" => [],
    //     "foreignkeys" => [],
    //     "charset" => "utf8",
    //     "prefix" => "tmp",
    //     "select" => "",
    //"where" => "",
    //     "ai" => "id",
    //     "engine" => "InnoDB",

    // ],
    // [
    //     "db" => "nci_test",
    //     "name" => "_all_time_dig31",
    //     "path" => "",
    //     "pr_key" => null,
    //     "indexes" => [],
    //     "foreignkeys" => [],
    //     "charset" => "utf8",
    //     "prefix" => "tmp",
    //     "select" => "",
    //"where" => "",
    //     "ai" => "id",
    //     "engine" => "InnoDB",

    // ],
    [
        "db" => "nci_test",
        "name" => "inv_tmp_contracts",
        "path" => "",
        "pr_key" => "id",
        "indexes" => ["ispol", "from_date", "str_kod"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "engine" => "InnoDB",

    ],
    [
        "db" => "nci_test",
        "name" => "inv_tmp_providers",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["kpost"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "engine" => "InnoDB",

    ],
    [
        "db" => "nci_test",
        "name" => "inv_tmp_country",
        "path" => "",
        "pr_key" => "id",
        "indexes" => ["code"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "engine" => "InnoDB",

    ],
    [
        "db" => "nci_test",
        "name" => "inv_tmp_units",
        "path" => "",
        "pr_key" => "unit_code",
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "engine" => "InnoDB",

    ],
    [
        "db" => "nci_test",
        "name" => "inv_tmp_goods",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["mat_code"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "engine" => "InnoDB",

    ],
    [
        "db" => "nci_test",
        "name" => "tmp_prof_level",
        "path" => "",
        "pr_key" => "gost",
        "indexes" => ["proff", "kprof", "level"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "engine" => "InnoDB",

    ],
    [
        "db" => "nci_test",
        "name" => "tmp_podr_all",
        "path" => "",
        "pr_key" => "code",
        "indexes" => ["kod_pr", "kod_sl", "kod_ceh", "kod_admu", "kod_master", "kod_brig", "date_from", "date_to"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "engine" => "InnoDB",

    ],
    [
        "db" => "nci_test",
        "name" => "nci_tmp_podr_all",
        "path" => "",
        "pr_key" => "code",
        "indexes" => ["kod_pr", "kod_sl", "kod_ceh", "kod_admu", "kod_master", "kod_brig", "date_from", "date_to"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "engine" => "InnoDB",

    ],



];
return [$config, $config_child];
