<?php

/**
 * Конфигурация для мигрирования данных из DBF в MySQL, справочники ПДПЛ
 */
$config = [
    [
		"db" => "pdpl",
        "name" => "kotp",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["tn","beg","endo"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "SELECT tn,npr,beg,endo,kind,ney,od,tn_rab FROM",
        "where" => "WHERE (DATE() BETWEEN beg AND endo) and (kind = 70 or kind=72)",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
	],
		[
        "db" => "pdpl",
        "name" => "r244",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "spr_alg",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "r254",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["gost"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "r254kkk",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "r254kpd",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "r252",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "r243sl",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "SELECT distinct kod_sl,kod_pr,nsl,knsl,priz_arh FROM ",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "r243admu",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "SELECT kod_pr,kod_ceh,kod_dir,kod_admu,nadmu,knadmu,priz_arh FROM ",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "r243ceh",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "SELECT kod_pr,kod_ceh,nceh,knceh,kod_gr,kod_sl,kod_vid,priz_arh FROM ",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "FSCHTAT",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["kprofpl","kod_pr","cex"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "r243",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "knap",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["tn","dol"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "SELECT tn,podr,dol,odpr From ",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	 [
        "db" => "pdpl",
        "name" => "education",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "SELECT tn,obr,u_z,dok,spec,kfd From",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "spr",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["kod","type"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "SELECT kk7 as type,kod,name From",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "uch_z",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["kod"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "SELECT kod,name_p,gorod_u From",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],

];

$config_child = [
    [
        "db" => "pdpl",
        "name" => "staff",
        "path" => "",
        "pr_key" => "id",
        "indexes" => ["kprofpl"],
        "foreignkeys" => [
            [
                "fk_name" => "fkpeople", "fk_col" => "tn_people",
                "fk_ref_table" => "people",
                "fk_ref_col" => "tn",
                "action_del" => "SET NULL",
                "action_upd" => "CASCADE"
            ]
        ],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => null,
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "pdpl",
        "name" => "people",
        "path" => "",
        "pr_key" => "tn",
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => null,
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "digest6",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "digest7",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "digest8",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "digest11",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "digest12",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
		[
        "db" => "pdpl",
        "name" => "digest16",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "digest19",
        "path" => null,
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [
            [
                // "fk_name" => "fkstaff", "fk_col" => "staff",
                // "fk_ref_table" => "staff",
                // "fk_ref_col" => "id",
                // "action_del" => "CASCADE",
                // "action_upd" => "CASCADE"
            ]
        ],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "digest26",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "digest28",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "digest29",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "digest30",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "digest36",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "digest37",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "digest39",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "digest46",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "digest47",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	    [
        "db" => "pdpl",
        "name" => "digest68",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
		    [
        "db" => "pdpl",
        "name" => "digest69",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "digest72",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    [
        "db" => "pdpl",
        "name" => "digest51",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "digest52",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["cex", "kod_pr", "kprofpl"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "digestEducation",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["tn"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
	[
        "db" => "pdpl",
        "name" => "digest81",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "id",
        "map" => [],
        "engine" => "InnoDB",
    ],
    // [
    //     "db" => "pdpl",
    //     "name" => "test",
    //     "path" => "",
    //     "pr_key" => null,
    //     "indexes" => [],
    //     "foreignkeys" => [],
    //     "charset" => "utf8",
    //     "prefix" => "",
    //     "select" => "",
    //"where" => "",
    //     "ai" => "id",
    //     "map" => [],
    //     "engine" => "InnoDB",
    // ],
];
return [$config, $config_child];
