<?php

$config = [

    [
        "db" => "tb",
        "name" => "R243PR",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => ["kod_pr" => "varchar(2)"],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "r243sl",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "r243admu",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "R243CEH",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "r243mbr",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "osdalu",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "r252",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "R148TEK",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "R254",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "R261",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "R103",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "GOROD",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "KL001",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "NS265",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "kosuv",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "knap",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "r_podch",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "r_podch_zbt",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "osdal",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "BSZ_R252",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

    [
        "db" => "tb",
        "name" => "R169",
        "path" => "",
        "pr_key" => null,
        "indexes" => [],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

];

$config_child = [
    [
        "db" => "tb",
        "name" => "tmp1",
        "path" => "",
        "pr_key" => null,
        "indexes" => ["tn", "fm", "podr", "gr_nkat", "prof", "pnprof", "nceh", "knsl"],
        "foreignkeys" => [],
        "charset" => "utf8",
        "prefix" => "m_",
        "select" => "",
        "where" => "",
        "ai" => "",
        "map" => [],
        "engine" => "InnoDB",
    ],

];
return [$config, $config_child];
